ecom/ecom/urls.py
"""
URL configuration for ecom project.

"""
from django.contrib import admin
from django.urls import path, include
from django.contrib. staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from . import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('bkndata/', include('bcknd.urls')),
    path('frnt/', include('frontnd.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/frontnd/urls.py
from django. urls import path
from . import views

app_name = 'frontnd' 

urlpatterns = [

    path('home/', views.home, name='home'),
    path('myaccount/', views.myaccount, name="myaccount"),
    path('cart/', views.cart, name="cart"),
    path('category/', views.category, name="category"),
    path('product/<catname>', views.product, name='product'),
    path('singleproduct/<int:id>', views.singleproduct, name="singleproduct"),
    path('contact/', views.contact, name='contact'),
    path('userlogn/', views.userlogn, name='userlogn'),
    path('userlogout/', views.userlogout, name='userlogout'),
    path('cartdelete/<int:id>', views.cartdelete, name='cartdelete'),
    path('whish/', views.whish, name='whish'),

]

ecom/frontnd/models.py
from django.db import models

# Create your models here.

class Register(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    password = models.CharField(max_length=100, null=True, blank=True)
    
class Contact(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    subject = models.CharField(max_length=100, null=True, blank=True)
    message = models.CharField(max_length=100, null=True, blank=True)
    
class cart(models.Model):
    image = models.ImageField(upload_to='media', null=True, blank=True)
    username = models.CharField(max_length=100, null=True, blank=True)
    productname = models.CharField(max_length=100, null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)
    totalprice = models.IntegerField(null=True, blank=True)

ecom/frontnd/views.py
from django.shortcuts import render, redirect
from bcknd.models import Category, Product
from frontnd . models import Contact, Register, cart

# Create your views here. 

def home(request):
    pro = Product.objects.all() 
    cate = Category.objects.all() 
    return render (request, 'home.html',{'pro':pro, 'cate':cate})

def myaccount(request):
    return render(request, 'myaccount.html')

def category(request):
    pro = Product.objects.all()
    cate = Category.objects.all()
    return render(request, 'category.html', {'pro':pro, 'cate':cate})

def product(request, catname):
    pro = Product.objects.filter(cname=catname) 
    cate = Category.objects.all()
    return render(request, 'product.html', {'pro':pro, 'cate':cate})

def singleproduct(request, id):
    cate = Category.objects.all()
    pro = Product.objects.get(id=id)
    return render(request, 'singleproduct.html',{'pro':pro, 'cate':cate})

def contact(request):
    if request.method=='POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        usr = Contact(name=name, email=email, subject=subject, message=message)
        usr.save()
    return render(request, 'contact.html')

def userlogn(request):
    if request.method=='POST':
        name = request.POST['name']
        password = request.POST['password']
        if Register.objects.filter(name=name, password=password).exists():
            request.session['name']=name
            request.session['password']=password
            return redirect(home)
        else:
            return redirect(userlogn)

    return render(request, 'userlogn.html')

def userlogout(request):
    del request.session['name']
    del request.session['password']
    return redirect(userlogn)

def cart(request):
    if request.method=='POST':
        image = request.FILES['image']
        username = request.POST['username']
        productname = request.POST['productname']
        quantity = request.POST['quantity']
        price = request.POST['price']
        totalprice = request.POST['totalprice']
        cartt=cart(image=image, username=username, productname=productname, quantity=quantity, price=price, totalprice=totalprice)
        cartt.save()
    return render(request, 'cart.html')

def cartdisplay(request):
    cate = Category.objects.all()
    cartt=cart.objects.filter(username=request.session['name'])
    return render(request, 'cart.html', {'cartt':cartt, 'cate':cate})

def cartdelete(request, id):
    cartt=cart.objects.get(id=id)
    cartt.delete()
    return redirect(cartdisplay)  

def whish(request):
    return render(request, 'whish list.html')

ecom/frontnd/templates/cateedit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body style="text-align: center;">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h1>Edit karooo</h1>
        <input type="text" name="name" placeholder="name" value="{{cate.category}}"><br><br>
        <input type="text" name="description" placeholder="Description" value="{{cate.description}}"><br><br>
        <img src="{{cate.media.url}}" width="100px"  height="100px" ><br><br>
        <input type="file" name="image" ><br><br>
        <button type="submit">REGISTER</button>
    </form>
</body>
</html>

ecom/frontnd/templates/logn.html
<!DOCTYPE html> 
{% load static %} 
<html lang="en"> 
<head> 
    <meta charset="UTF-8"> 
    <link rel="stylesheet" href="logn.css"> 
    <title>Document</title> 
</head>
<body style="background-color: cadetblue;">
    <!-- <div class="bkimg"> -->
    <!-- <img src="traveller.jpeg" alt=" " class="img"> -->
    <div class="row">
        <div col-md-6>
            <div class="mainbox">
                <div>
                    <h2 class="logg">.</h2>
                </div>
               
                <h1 style="text-align: center; font-family: 'poppins', sans-serif; " >Login / Register...</h1>
               
                <form action="" method="" enctype="multipart/form-data">
                     <!-- Email input -->
                    <div class="form_outline">
                        <label for="Email" class="email" >Username</label><br>
                        <input type="email" name="email" placeholder=" Enter Username" class="emailbox" id="jqinput1" ">
                        <hr  style="width: 300px;">
                    </div>
                    <div class="form_outline">
                        <label for="password" class="password" >Password</label><br>
                        <input type="password" name="email" placeholder=" Enter password" class="passwordbox" id="jqinput2" ">
                        <hr style="width: 300px;">
                    </div><br><br>
                    
                    <div class="row">
                        <div class="col">
                            <input class="check" type="checkbox">
                            <label for="" >Remember me</label>

                        </div>
                        <div class="forgt">
                            <button class="forgot"><a href="">FORGOT PASSWORD ?</a></button> 

                        </div>
                    </div>

                    <div class="col">
                        <p class="sign"> Or sign up using</p>
                    </div>
                    <div class="imag">
                        <img class="image" id="goo" src="{% static 'Home/img/banner/fbb.png' %}" >
                        <img class="image" id="go" src="{% static 'Home/img/banner/goog.png' %}">
                        <img class="image" id="goo" src="{% static 'Home/img/banner/twit.png' %}">

                    </div>
                    
                    <!-- Submit button -->
                    <button type="submit" class="sumit">SUBMIT</button>

                </form>

            </div>
        </div>
    </div>
    <style>
        
        .mainbox{
            margin: auto;
            margin-top: 50px;
            width: 400px;
            height: 500px;
            background: #ffffff;
            border-radius: 8px;
            opacity: 1.5px;
            box-shadow: rgb(151, 148, 148) 0px 1px 4px;
        }
        .h1{
            text-align: center;
            font-family: 'poppins', sans-serif;
            margin-top: 200px; 
        }
        .submit:hover{
            background-color: grey;
            color: chartreuse;
        }
        .sumit{
            width: 400px;
            height: 40px;
            border: none;
            border-radius: 5px;
            margin-left: 0px;
            margin-top: 30px;
        }
        .submit:hover{
            background-color: grey;
        }
        .email{
            margin-top: 200px;
            margin-left: 50px;
        }
        .emailbox{
            margin-left: 70px;
            margin-top: 10px;
            border: none;
            width: 270px;
            height: 30px;
            background-color: #ffffff;
            
        }
        .password{
            margin-left: 50px;
            margin-top: 10px;
        }
        .passwordbox{
            margin-left: 70px;
            border: none;
            margin-top: 10px;
            width: 270px;
            height: 30px;
            background-color: #ffffff;
            
        }
        .forgt{
            margin-top: -20px;
        }
        .forgot{
            border: none;
            margin-left: 190px;
            margin-top: -70px;
            font-size: 12px;

        }
        .check{
            margin-left: 50px;
            margin-top: 10px;
        }
        .sign{
            text-align: center;
            margin-top: 50px;
        }
        #goo{
            border-radius: 50%;
        }
        #go{
            border-radius: 50px;
        }
        .image{
            width: 25px;
            height: 25px;
        }
        .imag{
            text-align: center;
        }
        .logg{
            margin-top: 200px;
            color: white;
        }

    </style>

</body>
</html>

ecom/frontnd/templates/myaccount.html
<!DOCTYPE html>
{% load static %}
{% block content %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="icon" href="img/favicon.png" type="image/png" />
    <title>Eiser ecommerce</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'Home/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'Home/vendors/linericon/style.css' %}" />
    <link rel="stylesheet" href="{% static 'Home/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'Home/css/themify-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'Home/vendors/owl-carousel/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'Home/vendors/lightbox/simpleLightbox.css' %}" />
    <link rel="stylesheet" href="{% static 'Home/vendors/nice-select/css/nice-select.css' %}" />
    <link rel="stylesheet" href="{% static 'Home/vendors/animate-css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'Home/vendors/jquery-ui/jquery-ui.' %}" />
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'Home/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'Home/css/responsive.css' %}" />
  </head>

  <body>
    <!--================Header Menu Area =================-->
    <header class="header_area">
      <div class="top_menu">
        <div class="container">
          <div class="row">
            <div class="col-lg-7">
              <div class="float-left">
                <p>Phone: +01 256 25 235</p>
                <p>email: info@eiser.com</p>
              </div>
            </div>
            <div class="col-lg-5">
              <div class="float-right">
                <ul class="right_side">
                  <li>
                    <a href="{% url 'frontnd:myaccount' %}">
                      My account
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'frontnd:whish' %}">
                      Whish list
                    </a>
                  </li>
                  <li>
                    <a href="tracking.html">
                      Orders
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'frontnd:contact' %}">
                      Contact Us
                    </a>
                  </li>
                </ul>

                
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="main_menu">
        <div class="container">
          <nav class="navbar navbar-expand-lg navbar-light w-100">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand logo_h" href="index.html">
              <img src="img/logo.png" alt="" />
            </a>
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div
              class="collapse navbar-collapse offset w-100"
              id="navbarSupportedContent">
              <div class="row w-100 mr-0">
                <div class="col-lg-7 pr-0">
                  <ul class="nav navbar-nav center_nav pull-right">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'frontnd:home' %}">Home</a>
                    </li>
                    <li class="nav-item submenu dropdown">
                      <a
                        href="#"
                        class="nav-link dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-haspopup="true"
                        aria-expanded="false"
                        >Shop</a>
                      <ul class="dropdown-menu">
                        <li class="nav-item">
                          <a class="nav-link" href="category.html"
                            >Shop Category</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="single-product.html"
                            >Product Details</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="checkout.html"
                            >Product Checkout</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="cart.html">Shopping Cart</a>
                        </li>
                      </ul>
                    </li>
                    <li class="nav-item submenu dropdown">
                      <a href="{% url 'frontnd:category' %}" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                        aria-expanded="false">Category</a>
                        
                      <ul class="dropdown-menu">
                        {% for i in cate %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'frontnd:product' catname=i.category %}">{{i.category}}</a></li>
                        {% endfor %}
                      </ul>
                     
                    </li>
                    <li class="nav-item submenu dropdown">
                      <a
                        href="#"
                        class="nav-link dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-haspopup="true"
                        aria-expanded="false" >Pages</a>
                      <ul class="dropdown-menu">
                        <li class="nav-item">
                          <a class="nav-link" href="tracking.html">Tracking</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="elements.html">Elements</a>
                        </li>
                      </ul>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'frontnd:contact' %}">Contact</a>
                    </li>
                  </ul>
                </div>

                <div class="col-lg-5 pr-0">
                  <ul class="nav navbar-nav navbar-right right_nav pull-right">
                    <li class="nav-item">
                      <a href="#" class="icons">
                        <i class="ti-search" aria-hidden="true"></i>
                      </a>
                    </li>

                    <li class="nav-item">
                      <a href="{% url 'frontnd:cart' %}" class="icons">
                        <i class="ti-shopping-cart"></i>
                      </a>
                    </li>

                    <li class="nav-item">
                      <a href="{% url 'frontnd:contact' %}" class="icons">
                        <i class="ti-user" aria-hidden="true"></i>
                      </a>
                    </li>

                    <li class="nav-item">
                      <a href="{% url 'frontnd:whish' %}" class="icons">
                        <i class="ti-heart" aria-hidden="true"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </header>
    </body>
</html>
{% endblock %}
    <!--================Header Menu Area =================-->

    <!--================Home Banner Area =================-->
    <section class="banner_area">
      <div class="banner_inner d-flex align-items-center">
        <div class="container">
          <div
            class="banner_content d-md-flex justify-content-between align-items-center">
            <div class="mb-3 mb-md-0">
              <h1>Accouonts</h1>
              <p>Very us move be blessed multiply night</p>
            </div>
            <div class="page_link">
              <a href="{% url 'frontnd:home' %}">Home</a>
              <a href="{% url 'frontnd:contact' %}">Contact Us</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================End Home Banner Area =================-->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>

<section class="login_part section_padding ">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6">
                <div class="login_part_text text-center">
                    <div class="login_part_text_iner">
                      <img class="veggg" src="{% static 'Home/img/banner/bbbbb.jpeg' %}" alt="">
                        <h2 class="new">New to our Shop?</h2>
                        <p class="para">There are advances being made in science and technology<br> everyday, and a good example of this is the</p>
                        <button class="accbtn"><a href="#" class="acc">CREATE AN ACCOUNT</a></button>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="login_part_form">
                    <div class="login_part_form_iner">
                        <h3 class="wlcm">Welcome Back ! <br> Please Sign in now</h3>
                        <form class="row contact_form" action="#" method="post" novalidate="novalidate">
                        
                            <div class="col-md-12 form-group p_star" id="name">
                                <input type="text" class="form-control" id="name" name="name" value="" placeholder="Username" fdprocessedid="2545f">
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <input type="password" class="form-control" id="password" name="password" value="" placeholder="Password" fdprocessedid="v815bwk">
                            </div>
                            <div class="col-md-12 form-group">
                                <div class="creat_account d-flex align-items-center">
                                    <input type="checkbox" id="f-option" name="selector"><br><br>
                                    <label for="f-option" name="rer">Remember me</label>
                                </div>
                                <button type="submit" value="submit" class="btn_3" fdprocessedid="l50css">Log in</button>
                                <a class="lost_pass" href="#">forget password?</a>
                            </div>
                        </form>
                        <style>
                          .btn_3:hover{
                            background-color: rgb(130, 135, 215);
                            color: white;
                          }
                          .btn_3{
                            width: 550px;
                            border-radius: 5px;
                            
                            border-color: rgb(198, 212, 212);
                            background-color: rgb(213, 205, 205);
                            font-size: 19px;
                          }
                          .acc{
                            font-size: 14px;
                            color: crimson;
                          }
                          .accbtn{
                            width: 300px;
                            height: 40px;
                            opacity: 0.7px;
                            border-radius: 22px;
                            margin-top: 20px;
                          }
                          .wlcm:hover{
                            color: red;
                          }
                          .wlcm{
                            margin-top: 100px;
                            margin-left: 100px;
                            font-family: Georgia, 'Times New Roman', Times, serif;
                          }
                          .lost_pass{
                            margin-left: 400px;
                            margin-top: 300px;
                            
                          }
                          .veggg{
                            width: 100%;
                            height: 550px;

                          }
                          .new{
                            font-size: 30px;
                            color: crimson;
                            margin-top: -270px
  
                          }
                          .para{
                            font-size: 16px;
                            color: rgb(51, 50, 50);
                            margin-top: 30px;

                          }
                          #name{
                            margin-top: 20px;

                          }
                          .rer{
                            font-size: 22px;
                            color: red ;
                            margin-left: 12px;

                          }
                        </style>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>

ecom/frontnd/templates/userlogn.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Login V9</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data"> 
		{% csrf_token %}
        <div class="login-wrap">
            <div class="login-html">
                <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
                <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
                <div class="login-form">
                    <div class="sign-in-htm">
                        <div class="group">
                            <label for="user" class="label">Username</label>
                            <input id="user" name="name" type="text" class="input">
                        </div>
                        <div class="group">
                            <label for="pass" class="label">Password</label>
                            <input id="pass" name="password" type="password" class="input" data-type="password">
                        </div>
				<div class="group">
					<input id="check" type="checkbox" class="check" checked>
					<label for="check"><span class="icon"></span> Keep me Signed in</label>
				</div>
				<div class="group">
					<input type="submit" class="button" value="Sign In">
				</div>
				<div class="hr"></div>
				<div class="foot-lnk">
					<a href="#forgot">Forgot Password?</a>
				</div>
			</div>
                    <div class="sign-up-htm">
                        <div class="group">
                            <label for="user" class="label">Username</label>
                            <input id="user" type="text" class="input">
                        </div>
                        <div class="group">
                            <label for="pass" class="label">Email Address</label>
                            <input id="pass" type="text" class="input">
                        </div>
                        <div class="group">
                            <label for="pass" class="label">Password</label>
                            <input id="pass" type="password" class="input" data-type="password">
                        </div>
                        <div class="group">
                            <label for="pass" class="label">Confirm Password</label>
                            <input id="pass" type="password" class="input" data-type="password">
                        </div>
                        
                        <div class="group">
                            <input type="submit" class="button" value="Sign Up">
                        </div>
                        <div class="hr"></div>
                        <div class="foot-lnk">
                            <label for="tab-1">Already Member?</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>



<style>


body{
	margin:0;
	color:#6a6f8c;
	background:#c8c8c8;
	font:600 16px/18px 'Open Sans',sans-serif;
}
*,:after,:before{box-sizing:border-box}
.clearfix:after,.clearfix:before{content:'';display:table}
.clearfix:after{clear:both;display:block}
a{color:inherit;text-decoration:none}

.login-wrap{
	width:100%;
	margin:auto;
	max-width:525px;
	min-height:670px;
	position:relative;
	background:url(https://raw.githubusercontent.com/khadkamhn/day-01-login-form/master/img/bg.jpg) no-repeat center;
	box-shadow:0 12px 15px 0 rgba(0,0,0,.24),0 17px 50px 0 rgba(0,0,0,.19);
}
.login-html{
	width:100%;
	height:100%;
	position:absolute;
	padding:90px 70px 50px 70px;
	background:rgba(40,57,101,.9);
}
.login-html .sign-in-htm,
.login-html .sign-up-htm{
	top:0;
	left:0;
	right:0;
	bottom:0;
	position:absolute;
	transform:rotateY(180deg);
	backface-visibility:hidden;
	transition:all .4s linear;
}
.login-html .sign-in,
.login-html .sign-up,
.login-form .group .check{
	display:none;
}
.login-html .tab,
.login-form .group .label,
.login-form .group .button{
	text-transform:uppercase;
}
.login-html .tab{
	font-size:22px;
	margin-right:15px;
	padding-bottom:5px;
	margin:0 15px 10px 0;
	display:inline-block;
	border-bottom:2px solid transparent;
}
.login-html .sign-in:checked + .tab,
.login-html .sign-up:checked + .tab{
	color:#fff;
	border-color:#1161ee;
}
.login-form{
	min-height:345px;
	position:relative;
	perspective:1000px;
	transform-style:preserve-3d;
}
.login-form .group{
	margin-bottom:15px;
}
.login-form .group .label,
.login-form .group .input,
.login-form .group .button{
	width:100%;
	color:#fff;
	display:block;
}
.login-form .group .input,
.login-form .group .button{
	border:none;
	padding:15px 20px;
	border-radius:25px;
	background:rgba(255,255,255,.1);
}
.login-form .group input[data-type="password"]{
	
	-webkit-text-security:circle;
}
.login-form .group .label{
	color:#aaa;
	font-size:12px;
}
.login-form .group .button{
	background:#1161ee;
}
.login-form .group label .icon{
	width:15px;
	height:15px;
	border-radius:2px;
	position:relative;
	display:inline-block;
	background:rgba(255,255,255,.1);
}
.login-form .group label .icon:before,
.login-form .group label .icon:after{
	content:'';
	width:10px;
	height:2px;
	background:#fff;
	position:absolute;
	transition:all .2s ease-in-out 0s;
}
.login-form .group label .icon:before{
	left:3px;
	width:5px;
	bottom:6px;
	transform:scale(0) rotate(0);
}
.login-form .group label .icon:after{
	top:6px;
	right:0;
	transform:scale(0) rotate(0);
}
.login-form .group .check:checked + label{
	color:#fff;
}
.login-form .group .check:checked + label .icon{
	background:#1161ee;
}
.login-form .group .check:checked + label .icon:before{
	transform:scale(1) rotate(45deg);
}
.login-form .group .check:checked + label .icon:after{
	transform:scale(1) rotate(-45deg);
}
.login-html .sign-in:checked + .tab + .sign-up + .tab + .login-form .sign-in-htm{
	transform:rotate(0);
}
.login-html .sign-up:checked + .tab + .login-form .sign-up-htm{
	transform:rotate(0);
}

.hr{
	height:2px;
	margin:60px 0 50px 0;
	background:rgba(255,255,255,.2);
}
.foot-lnk{
	text-align:center;
}
</style>

</body>
</html>